name: nlp-2021
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - datasets
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - nltk
  - seaborn
  - wandb # experiment mgr
  - pytest
  - pyhamcrest
  - pip
  - pip:
    - gensim