name: nlp-2-2021
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter
  - datasets
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - nltk
  - pytorch
  - seaborn
  - gensim
  - hydra # config
  - omegaconf # config
  - mlflow # experiment mgr
  - pytest
  - pyhamcrest